ewf:
  bath_threshold: 1.0e-05
  solver: SCI
  sci_select_cutoff: 0.001
  multi_solver:
    enabled: true
    norb_threshold: 13
    high_accuracy_solver: FCI
    approximate_solver: SQD
  assembly: rdm_t_lambda
calculation:
  run_mode: ewf
  geometry_file: /mnt/beegfs/merzk/kaliakd/EWF_Geom_Opt_Development/5_test_SQD_deployment/ethene_sqd_test/jobs_EWF/step_007/geometry.txt
  basis: sto-3g
  charge: 0
  spin: 0
  symmetry: false
  workdir: /mnt/beegfs/merzk/kaliakd/EWF_Geom_Opt_Development/5_test_SQD_deployment/ethene_sqd_test/jobs_EWF/step_007
  fci_conv_tol: 1.0e-12
slurm:
  python_executable: python
  poll_interval: 15
  dump:
    partition: bigmem
    ntasks: 2
    mem: 100G
  FCI:
    partition: bigmem
    ntasks: 2
    mem: 10G
  SQD:
    partition: bigmem
    ntasks: 2
    mem: 100G
  SCI: {}
  SCI_SBD: {}
sqd:
  sbd_exe_path_cpu: /mnt/beegfs/merzk/kaliakd/Software/SBD_Solver/executable/diag
  sbd_exe_path_gpu: /home/liz7/isilon/Zhen/sbd-main/apps/test/diag
  mpi_launcher: /home/liz7/isilon/Zhen/mpich/bin/mpirun
  proc_type: 1
  gpus_per_batch: 4
  cpus_per_gpu: 16
  sbd_omp_threads: 1
  sbd_block: 20
  sbd_dav_iteration: 10
  sbd_tolerance: 1.0e-05
  sbd_init: 0
  sbd_shuffle: 0
  sbd_carryover_ratio: 0.5
  iterations: 5
  n_batches: 3
  samples_per_batch: 2000
  energy_tol: 1.0e-08
  occupancies_tol: 1.0e-05
  carryover_threshold: 0.0001
  symmetrize_spin: true
  add_hf_string: true
  ext_sqd_dprime_cutoff: 1.0e-05
  sample_on_the_fly: true
  qiskit_backend: ibm_cleveland
  default_shots: 100000
  n_reps: 1
  thresh_two_q: 1.0
  thresh_meas: 0.1
  slurm:
    poll_interval: 15
    max_node_retries: 5
    preamble: 'module load gcc/11.2.0 cuda12.3/toolkit/12.3.2 cudnn8.9-cuda12.3/8.9.7.29
      boost/1.85.0

      export PATH="/home/liz7/isilon/Zhen/mpich/bin:$PATH"

      export LD_LIBRARY_PATH="/home/liz7/beegfs/liz7/openblasgpu/lib:$LD_LIBRARY_PATH"

      export PATH="/home/liz7/beegfs/liz7/openblasgpu/bin:$PATH"

      '
    sbatch:
      partition: merzk-a100
      mem: 500G
      extra:
        exclude: m002
geomopt:
  enabled: true
  optimizer: sella
  prefix: ewf_geomopt
  step_subdir_fmt: step_{step:03d}
  sella:
    fmax: 0.01
    steps: 20
    order: 0
    internal: true
  geometric:
    maxiter: 100
    coordsys: tric
    convergence_set: GAU
  berny: {}
